#!/bin/bash

# Küsi kasutajalt suvaline  täisarv
read -p "Sisesta suvaline täisarv: " arv

# Alusta summa muutuja väärtusega 0
summa=0

# Käi läbi iga numbri arvust
while [ $arv -ne 0 ]; do
    # Leia viimane number
    number=$((arv % 10))
    # Lisa number summale
    summa=$((summa + number))
    # Eemalda viimane number arvust
    arv=$((arv / 10))
done

# Väljasta tulemus
echo "Arvu $1 numbrite summa on $summa"
