#!/bin/bash

#
# See skript võimaldab kasutajal sisestada kuu numbri (1-12).
# Vastavalt sisestatud kuu numbrile väljastatakse kuu nimetus.
# Muude väärtuste korral väljastatakse veateade.

# Küsi kasutajalt kuu number
read -p "Sisesta kuu number (1-12): " kuu

# Kontrolli, kas sisend on vahemikus 1-12
if [ $kuu -ge 1 -a $kuu -le 12 ]; then
    case $kuu in
        1) echo "See on jaanuar" ;;
        2) echo "See on veebruar" ;;
        3) echo "See on märts" ;;
        4) echo "See on aprill" ;;
        5) echo "See on mai" ;;
        6) echo "See on juuni" ;;
        7) echo "See on juuli" ;;
        8) echo "See on august" ;;
        9) echo "See on september" ;;
        10) echo "See on oktoober" ;;
        11) echo "See on november" ;;
        12) echo "See on detsember" ;;
    esac
else
    echo "Vigane sisend! Sisesta korrektne kuu number."
fi
